### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

**Creating Numpy Arrays**

In [1]:
# np.array
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
# 2D and 3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [ ]:
# np.arange - range function in python
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
# with reshape

# Basic use
a = np.arange(1, 11).reshape(5,2)
print(a)

# Another way -> The product must be equal to the size of an array
b = np.arange(16).reshape(2, 2, 4)
print(b)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [ ]:
# np.ones and np.zeros - Mostly used in Neural Networks for creating instant arrays
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((3,4), dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

**np.random functions**

In [7]:
# np.random
np.random.random((3,4))

# another variations
np.random.randint(1, 10, size = 6)

# Fancy indexing - Explained in Advance numpy notebook
print(np.random.randint(1, [3, 5, 10, 11])) # Explain ?
np.random.randint([1, 5, 7], 10) # Explain ?

[1 4 7 7]


array([4, 7, 9])

In [ ]:
# np.linspace
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [ ]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Array Attributes**

In [ ]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# ndim - no. of layers
a3.ndim

3

In [ ]:
# shape - no.of elements present in each layer
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# size
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
# itemsize
a3.itemsize

8

In [ ]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)



int32
float64
int64


**Changing Datatype**

In [ ]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

**Array Operations**

*While doing operations between two vectors the array shape must be same*

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# scalar operations

# arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [6]:
temp = np.arange(1, 11).reshape(2, 5)
temp2 = np.arange(1, 11).reshape(5, 2)

temp + temp2 # Array broadcansing

ValueError: operands could not be broadcast together with shapes (2,5) (5,2) 

In [ ]:
# relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
# vector operations
# arithmetic
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

**Array Functions**

In [9]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1
# 2.5 round - 2

array([[24., 68., 87.],
       [86., 75., 37.],
       [59., 59., 20.]])

**Aggrigation Functions**

In [ ]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.prod(a1,axis=0)

array([35991., 46872., 17892.])

In [ ]:
# mean/median/std/var
np.var(a1,axis=1)

array([317.55555556, 854.        ,  96.22222222])

In [ ]:
# trigonomoetric functions
np.sin(a1)

array([[-0.83177474,  0.27090579,  0.95105465],
       [ 0.95637593, -0.94828214, -0.99177885],
       [-0.40403765, -0.75098725,  0.6569866 ]])

**dot product**

In [ ]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

**Difference between dot and (multiply sign) functions for doing multiplication of two arrays**

In [7]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a * b) # here each element is multiplied with its corrosponding positional element of other array

print(np.prod(a)) # Product of all elements in a single array

c = np.reshape(len(b), 1)
print(np.dot(a, b)) # No. of columns of 1st array = No. of rows of 2nd array

[ 4 10 18]
6
32


In [10]:
# log and exponents
np.exp(a1)

np.log(a1)

array([[3.17805383, 4.21950771, 4.46590812],
       [4.4543473 , 4.31748811, 3.61091791],
       [4.07753744, 4.07753744, 2.99573227]])

In [ ]:
# round/floor/ceil

np.ceil(np.random.random((2,3))*100)

array([[48.,  4.,  6.],
       [ 3., 18., 82.]])

**Indexing and Slicing**

In [11]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [18]:
# Indexing and slicing in 1D array
print(a1[len(a1) - 2])
print(a1[5:0:-1]) # for reversed array (-1) the first number must be greater than second

# Indexing and slicing in 2D array
print(a2[2, 2])
print(a2[[0, 2], 1::]) # Fancy indexing

# Indexing and slicing in 3D array
print(a3[1,1,1])
print(a3[::, 0:1:, ::])

8
[5 4 3 2 1]


In [ ]:
a2[1,0] # 1st dimention - row | 2nd dimention column for 2D

4

In [ ]:
a3[1,0,1] # How this 3 numbers are represented - External to internal

5

In [ ]:
a1[2:5:2] # accessing elements with strids

array([2, 4])

**Accessing elements in 2d and 3d array**

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[::2, 0:4:3]

array([[ 0,  3],
       [ 8, 11]])

In [ ]:
a2[0,:]

array([0, 1, 2, 3])

In [ ]:
a2[:,2] #Imp

array([ 2,  6, 10])

In [ ]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

**Accessing elements in 3d array**

In [ ]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [ ]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [ ]:
a3[0,1,:]

array([3, 4, 5])

**Iterating**

In [ ]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


**Reshaping**

In [ ]:
# Transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
# ravel
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

**Stacking**

In [ ]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [2]:
# 1D Stacking
a1 = np.array([1,2,3,4])
a2 = np.array([10, 20, 30, 40])

np.hstack((a1, a2))
# np.vstack((a1, a2))

array([ 1,  2,  3,  4, 10, 20, 30, 40])

In [4]:
# 2D Stacking
a1 = np.random.randint(0, 10, size = (5, 2))
a2 = np.random.randint(0, 10, size = (5, 2))
print(a1, a2)

[[1 5]
 [4 6]
 [7 6]
 [5 5]
 [8 8]] [[8 7]
 [6 3]
 [1 6]
 [3 5]
 [0 3]]


In [6]:
# np.hstack((a1, a2))
np.vstack((a1, a2))

array([[1, 5],
       [4, 6],
       [7, 6],
       [5, 5],
       [8, 8],
       [8, 7],
       [6, 3],
       [1, 6],
       [3, 5],
       [0, 3]])

In [9]:
# 3D Stacking
a1 = np.random.randint(0, 9, size = (2,2,2))
a2 = np.random.randint(0, 9, size = (2,2,2))
print(a1, a2)

[[[0 0]
  [6 5]]

 [[8 2]
  [4 5]]] [[[7 6]
  [1 0]]

 [[3 8]
  [0 3]]]


In [11]:
np.vstack((a1, a2))
# np.hstack((a1, a2))

array([[[0, 0],
        [6, 5]],

       [[8, 2],
        [4, 5]],

       [[7, 6],
        [1, 0]],

       [[3, 8],
        [0, 3]]])

**Splitting**

In [ ]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.hsplit(a4,4)
# The splitting must be homogonous on both the side then only this function will not throw an error

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [ ]:
# vertical splitting
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]